### PR TITLE
Add graphql-code-generator to Typescript and Flow

### PR DESCRIPTION
**Pull request by Urigo**
Add graphql-code-generator to Typescript and Flow sections

### CODE REVIEW

**Comment by stereobooster** [comment]
Thank you. Link to live demo https://graphql-code-generator.com/#live-demo would make more sense, but on the other side it loads slowly (without any graphical identification) so it can be confusing

**Comment by Urigo** [comment]
mmm good point, I can fix it if you want

**Comment by stereobooster** [comment]
To be honest, I have no strong opinion here. If you want you can fix it

**Comment by Urigo** [comment]
I'll leave it for now like that, but cutting down the loading time would be a good idea

**Pull request merged**
